"""Validated built-in Template and Quick Action catalogue."""

BUILTIN_TEMPLATE_BUNDLE = {'format': 'openscribe-template-bundle',
 'format_version': 1,
 'templates': [{'name': 'Daily Driver',
                'description': 'A simple consult, good for most things.',
                'latest_version': {'mode': 'structured',
                                   'prompt_text': 'You are a medical secretary who works in the '
                                                  'UK. You will take in a transcript from a doctor '
                                                  'patient consult. You will not infer or add any '
                                                  'new information other than what is in the '
                                                  'transcript. These notes are for the medical '
                                                  'professionals to read, thus you should use UK '
                                                  'terminology and medical jargon. \r\n'
                                                  'The note must be from the perspective of the '
                                                  'doctor - therefore use the first person for '
                                                  'things the doctor thinks. \r\n'
                                                  'If any segments are not mentioned in the '
                                                  'transcript, leave them blank, do not say "not '
                                                  'mentioned".\r\n'
                                                  'Each statement needs a new line between it so '
                                                  'that it is rendered in the note viewer '
                                                  'properly. This must be adhered to.\r\n'
                                                  "You're really terse and only document things "
                                                  'that are really important.',
                                   'config_json': {'profile': 'emis',
                                                   'sections': [{'section_key': 'problem',
                                                                 'instruction': 'A single disease '
                                                                                'entity, this is '
                                                                                'the SNOMED code '
                                                                                'for the main '
                                                                                'issue that is '
                                                                                'discussed.',
                                                                 'section_order': 1},
                                                                {'section_key': 'history',
                                                                 'instruction': 'This is the '
                                                                                'patients issue, '
                                                                                'symptoms and '
                                                                                'signs, as well as '
                                                                                'their background '
                                                                                'medical '
                                                                                'history. \r\n'
                                                                                'Start with the '
                                                                                'patients '
                                                                                '"agenda", the '
                                                                                'thing that they '
                                                                                'came to get '
                                                                                'assessed / what '
                                                                                'they wanted. e.g '
                                                                                '"Face to face / '
                                                                                'tel appointment '
                                                                                'for cough, '
                                                                                'worried about '
                                                                                'infection"\r\n'
                                                                                'Then set the '
                                                                                'scene, with a few '
                                                                                'lines of prose '
                                                                                'that outlines the '
                                                                                'signs and '
                                                                                'symptoms the '
                                                                                'patient had, how '
                                                                                'it affected them '
                                                                                'and what they '
                                                                                'tried for it. \r\n'
                                                                                'This should set '
                                                                                'the scene of why '
                                                                                'the patient is '
                                                                                'here and is going '
                                                                                'to be their '
                                                                                'opening gambit '
                                                                                'that they deliver '
                                                                                'to the '
                                                                                'doctor. \r\n'
                                                                                'Make it into a '
                                                                                'cogent story that '
                                                                                'describes '
                                                                                'timelines, '
                                                                                'severity, things '
                                                                                'tried. \r\n'
                                                                                'Then switch to a '
                                                                                'more bullet point '
                                                                                'list style.\r\n'
                                                                                'Each line should '
                                                                                'be a factual '
                                                                                'statement from '
                                                                                'the '
                                                                                'transcript.\r\n'
                                                                                'All lines need '
                                                                                'new lines between '
                                                                                'them.\r\n'
                                                                                '\r\n'
                                                                                'The doctor will '
                                                                                'likely ask a set '
                                                                                'of closed '
                                                                                'questions, '
                                                                                'outline the '
                                                                                'answers to these, '
                                                                                'give them a new '
                                                                                'line each.\r\n'
                                                                                'Take into account '
                                                                                'the doctors end '
                                                                                'of transcript '
                                                                                'dictation as this '
                                                                                'should steer what '
                                                                                'details are '
                                                                                'important or not '
                                                                                'from the '
                                                                                'patient. \r\n'
                                                                                'Then ICE: Ideas '
                                                                                '(what the patient '
                                                                                'thinks it could '
                                                                                'be) Concerns '
                                                                                '(what they are '
                                                                                'worried it might '
                                                                                'be) Expectations '
                                                                                '(what they were '
                                                                                'expecting the '
                                                                                'doctor to do)\r\n'
                                                                                'Any red flags '
                                                                                'explicitly '
                                                                                'confirmed or '
                                                                                'denied. It is '
                                                                                'important to '
                                                                                'include those red '
                                                                                'flags which the '
                                                                                'doctor asked '
                                                                                'about, but were '
                                                                                'explicitly '
                                                                                'denied. \r\n'
                                                                                '\r\n'
                                                                                'Past medical '
                                                                                'history:\r\n'
                                                                                'List of pmh\r\n'
                                                                                'Medications:\r\n'
                                                                                'List of '
                                                                                'medications',
                                                                 'section_order': 2},
                                                                {'section_key': 'family_history',
                                                                 'instruction': 'The relevant '
                                                                                'family history of '
                                                                                'the patient, if '
                                                                                'discussed.\r\n'
                                                                                'Can leave blank '
                                                                                'if not mentioned',
                                                                 'section_order': 3},
                                                                {'section_key': 'social_history',
                                                                 'instruction': 'The patients '
                                                                                'living, working '
                                                                                'and life '
                                                                                'situation. Their '
                                                                                'meaningful '
                                                                                'relationships and '
                                                                                'their effects on '
                                                                                'them. \r\n'
                                                                                'Also their '
                                                                                'drinking, smoking '
                                                                                'and recreational '
                                                                                'drug habits.\r\n'
                                                                                'Can leave blank '
                                                                                'if not mentioned',
                                                                 'section_order': 4},
                                                                {'section_key': 'examination',
                                                                 'instruction': 'The exam findings '
                                                                                'separated by '
                                                                                'system and '
                                                                                'side. \r\n'
                                                                                'Then any vital '
                                                                                'such as BP, HR, '
                                                                                'temperature, '
                                                                                'respiratory rate, '
                                                                                'oxygen saturation '
                                                                                '- each of these '
                                                                                'needs a new line '
                                                                                'and a : after '
                                                                                'them.\r\n'
                                                                                'Can leave blank '
                                                                                'if not mentioned',
                                                                 'section_order': 5},
                                                                {'section_key': 'comment',
                                                                 'instruction': 'The overall '
                                                                                'impression of the '
                                                                                'doctor, including '
                                                                                'any '
                                                                                'differentials. \r\n'
                                                                                'This would '
                                                                                'include any '
                                                                                'explanations '
                                                                                'given to the '
                                                                                'patient. \r\n'
                                                                                'Then the plan '
                                                                                'that was '
                                                                                'discussed with '
                                                                                'the patient, '
                                                                                'things that the '
                                                                                'patient has '
                                                                                'agreed to do.\r\n'
                                                                                'Then the safety '
                                                                                'netting that was '
                                                                                'provided.',
                                                                 'section_order': 6},
                                                                {'section_key': 'tasks',
                                                                 'instruction': 'Any tasks that '
                                                                                'the doctor has '
                                                                                'said they will '
                                                                                'do.',
                                                                 'section_order': 7},
                                                                {'section_key': 'investigations',
                                                                 'instruction': 'Any blood tests '
                                                                                'that are planned, '
                                                                                'as comma '
                                                                                'separated list. '
                                                                                '(FBC, U&E, LFT '
                                                                                'etc)',
                                                                 'section_order': 8}]}}},
               {'name': 'GP Note',
                'description': 'Un-sectioned GP Note for multiple issues',
                'latest_version': {'mode': 'freeform',
                                   'prompt_text': '[Consultation type: face-to-face "F2F" or '
                                                  'telephone "T/C"] (Only include if explicitly '
                                                  'mentioned in the transcript, contextual notes '
                                                  'or clinical note; otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  '[People present during consultation, e.g. seen '
                                                  'alone or with someone] (Only include if '
                                                  'explicitly mentioned in the transcript, '
                                                  'contextual notes or clinical note; otherwise '
                                                  'omit entirely.)\r\n'
                                                  '\r\n'
                                                  '[Reason for visit such as whether this is a '
                                                  'follow up, booking note, current issues, etc ] '
                                                  '(Only include if explicitly mentioned in the '
                                                  'transcript, contextual notes or clinical note; '
                                                  'otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  'History:\r\n'
                                                  '\r\n'
                                                  '- [History of presenting complaints] (Only '
                                                  'include if explicitly mentioned in the '
                                                  'transcript, contextual notes or clinical note; '
                                                  'otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  "- ICE: [Patient's Ideas, Concerns and "
                                                  'Expectations] (Only include if explicitly '
                                                  'mentioned in the transcript, contextual notes '
                                                  'or clinical note; otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- Red Flag: [Red flag symptoms relevant to the '
                                                  'presenting complaint] (Only include if '
                                                  'explicitly mentioned in the transcript, '
                                                  'contextual notes or clinical note; otherwise '
                                                  'omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- Risk Factors: [Relevant risk factors] (Only '
                                                  'include if explicitly mentioned in the '
                                                  'transcript, contextual notes or clinical note; '
                                                  'otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- PMH/PSH: [Past medical or surgical history] '
                                                  '(Only include if explicitly mentioned in the '
                                                  'transcript, contextual notes or clinical note; '
                                                  'otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- DH: [Drug history or medications] (Only '
                                                  'include if explicitly mentioned in the '
                                                  'transcript, contextual notes or clinical note; '
                                                  'otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- Allergies: [Allergies] (Only include if '
                                                  'explicitly mentioned in the transcript, '
                                                  'contextual notes or clinical note; otherwise '
                                                  'omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- FH: [Relevant family history] (Only include '
                                                  'if explicitly mentioned in the transcript, '
                                                  'contextual notes or clinical note; otherwise '
                                                  'omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- SH: [Social history including living '
                                                  'situation, occupation, smoking, alcohol, drugs, '
                                                  'travel or carers] (Only include if explicitly '
                                                  'mentioned in the transcript, contextual notes '
                                                  'or clinical note; otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  'Examination:\r\n'
                                                  '\r\n'
                                                  '- [Vital signs] (Only include if explicitly '
                                                  'mentioned in the transcript, contextual notes '
                                                  'or clinical note; otherwise omit entirely. List '
                                                  'in the order: T for temperature, Sats % for '
                                                  'oxygen saturation, HR for heart rate, BP for '
                                                  'blood pressure, RR for respiratory rate.)\r\n'
                                                  '\r\n'
                                                  '- [Physical or mental state examination '
                                                  'findings including system-specific findings] '
                                                  '(Only include if explicitly mentioned in the '
                                                  'transcript, contextual notes or clinical note; '
                                                  'otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- [Investigations and results] (Only include if '
                                                  'explicitly mentioned in the transcript, '
                                                  'contextual notes or clinical note; otherwise '
                                                  'omit entirely.)\r\n'
                                                  '\r\n'
                                                  'Impression:\r\n'
                                                  '\r\n'
                                                  '[Clinical impression or problems identified by '
                                                  'the clinician] (Only include if explicitly '
                                                  'mentioned in the transcript, contextual notes '
                                                  'or clinical note; otherwise omit entirely. Do '
                                                  'not infer or assume a diagnosis.)\r\n'
                                                  '\r\n'
                                                  '1. [Diagnoses or differential/likely diagnoses '
                                                  'as mentioned by the clinician] (Only include if '
                                                  'explicitly mentioned in the transcript, '
                                                  'contextual notes or clinical note; otherwise '
                                                  'omit entirely. Do not infer or assume a '
                                                  'diagnosis. Write as a numbered list. Add a “?” '
                                                  'before every differential diagnosis.)\r\n'
                                                  '\r\n'
                                                  'Plan:\r\n'
                                                  '\r\n'
                                                  '- [Investigations] (Only include if explicitly '
                                                  'mentioned in the transcript, contextual notes '
                                                  'or clinical note; otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- [Treatment plans including medications if '
                                                  'discussed] (Only include if explicitly '
                                                  'mentioned in the transcript, contextual notes '
                                                  'or clinical note; otherwise omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- [Referrals required or advised] (Only include '
                                                  'if explicitly mentioned in the transcript, '
                                                  'contextual notes or clinical note; otherwise '
                                                  'omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- [Follow-up arrangements including timeframe, '
                                                  'setting or instructions] (Only include if '
                                                  'explicitly mentioned in the transcript, '
                                                  'contextual notes or clinical note; otherwise '
                                                  'omit entirely.)\r\n'
                                                  '\r\n'
                                                  '- Safety netting advice: [Symptoms or '
                                                  'situations requiring GP call-back, 111 contact '
                                                  'or A&E/999 attendance as appropriate] (Only '
                                                  'include if explicitly mentioned in the '
                                                  'transcript, contextual notes or clinical note; '
                                                  'otherwise omit entirely.)',
                                   'config_json': None}},
               {'name': 'GLP1 Review',
                'description': None,
                'latest_version': {'mode': 'freeform',
                                   'prompt_text': 'You are to fill out the following form given '
                                                  'the info in the transcript. If a section is not '
                                                  'addressed, leave it empty. Do not add any '
                                                  'informatoin. \r\n'
                                                  '\r\n'
                                                  ':\r\n'
                                                  'Any problems with injections? -\r\n'
                                                  'Any side effects or suspected reactions? -\r\n'
                                                  'Any concerns about low micronutrient intake? '
                                                  '-\r\n'
                                                  'Are supplements needed? -\r\n'
                                                  'Any plans for pregnancy? -\r\n'
                                                  'Any extra support needed with diet or physical '
                                                  'activity? -\r\n'
                                                  'What progress has been made against the initial '
                                                  'goals? -\r\n'
                                                  '\r\n'
                                                  'Measurements:\r\n'
                                                  'Height -\r\n'
                                                  'Weight -\r\n'
                                                  'Waist circumference, if BMI is under 35 -\r\n'
                                                  'Other checks related to existing health '
                                                  'conditions -\r\n'
                                                  '\r\n'
                                                  'Calculate:\r\n'
                                                  'BMI -\r\n'
                                                  'Waist-to-height ratio, if BMI is under 35 -\r\n'
                                                  '\r\n'
                                                  'Dose:\r\n'
                                                  'Increase dose by 2.5 mg if tolerated and not '
                                                  'already at 15 mg? -\r\n'
                                                  '\r\n'
                                                  'Health conditions and medicines:\r\n'
                                                  'Review existing health conditions -\r\n'
                                                  'Adjust other medicines if needed -\r\n'
                                                  'Do any oral narrow therapeutic index medicines '
                                                  'need monitoring? -\r\n'
                                                  '\r\n'
                                                  'Referrals:\r\n'
                                                  'Does the patient need referral to other '
                                                  'services, such as social care, physiotherapy, '
                                                  'or mental health support? -\r\n'
                                                  '\r\n'
                                                  'Counselling:\r\n'
                                                  'Explain any dose changes -\r\n'
                                                  'Discuss additional contraceptive measures if '
                                                  'needed -\r\n'
                                                  'Discuss reduced-calorie diet and increased '
                                                  'physical activity -',
                                   'config_json': None}},
               {'name': 'Depression',
                'description': 'For a consult focussing on depressive symptoms',
                'latest_version': {'mode': 'structured',
                                   'prompt_text': 'This is a template for turning a consult about '
                                                  'a patient presenting with or having a review of '
                                                  'their depression. \r\n'
                                                  'Use UK spellings. \r\n'
                                                  'You are a secretary who transcribes the '
                                                  'conversation into the template without adding '
                                                  'any new content.',
                                   'config_json': {'profile': 'emis',
                                                   'sections': [{'section_key': 'problem',
                                                                 'instruction': 'Depression /\r\n'
                                                                                'Depression and '
                                                                                'anxiety',
                                                                 'section_order': 1},
                                                                {'section_key': 'history',
                                                                 'instruction': 'Begin with short '
                                                                                'overview of the '
                                                                                'patients story of '
                                                                                'their mental '
                                                                                'health, as a '
                                                                                'block of '
                                                                                'prose.\r\n'
                                                                                'Presents '
                                                                                'with...\r\n'
                                                                                '\r\n'
                                                                                'Then new lines '
                                                                                'for each of these '
                                                                                'aspects;\r\n'
                                                                                'Sleep: (where is '
                                                                                'the difficulty? '
                                                                                'Initiation / '
                                                                                'broken / sleeping '
                                                                                'too much but '
                                                                                'still tired etc. '
                                                                                ')\r\n'
                                                                                'Concentration: '
                                                                                '(preserved / '
                                                                                'moderate / '
                                                                                'poor)\r\n'
                                                                                'Appetite: (Grade '
                                                                                'their '
                                                                                'appetite.)\r\n'
                                                                                'Self Care:(How '
                                                                                'much have they '
                                                                                'been eating, have '
                                                                                'they been '
                                                                                'washing, '
                                                                                'cleaning, '
                                                                                'dressing, tidying '
                                                                                'the house etc)\r\n'
                                                                                'Anhedonia: (how '
                                                                                'much are they '
                                                                                'enjoying the '
                                                                                'things they '
                                                                                'usually would, '
                                                                                'looking forward '
                                                                                'to anything in '
                                                                                'the future?)\r\n'
                                                                                'Libido: (Effect '
                                                                                'on libido)\r\n'
                                                                                '\r\n'
                                                                                'Protective '
                                                                                'factors:\r\n'
                                                                                'Anything that '
                                                                                'they say makes '
                                                                                'them stick '
                                                                                'around \r\n'
                                                                                '\r\n'
                                                                                'Risk '
                                                                                'assessment:\r\n'
                                                                                'Document only '
                                                                                'risks explicitly '
                                                                                'assessed or '
                                                                                'disclosed.\r\n'
                                                                                'Suicidal '
                                                                                'thoughts\r\n'
                                                                                'Frequency and '
                                                                                'duration of '
                                                                                'suicidal '
                                                                                'thoughts\r\n'
                                                                                'Suicidal '
                                                                                'intent\r\n'
                                                                                'Suicide plan\r\n'
                                                                                'Access to '
                                                                                'means\r\n'
                                                                                'Preparatory '
                                                                                'acts\r\n'
                                                                                'Previous suicide '
                                                                                'attempts\r\n'
                                                                                'Self-harm '
                                                                                'thoughts\r\n'
                                                                                'Current or recent '
                                                                                'self-harm\r\n'
                                                                                'Previous '
                                                                                'self-harm\r\n'
                                                                                'Thoughts or '
                                                                                'intent to harm '
                                                                                'others\r\n'
                                                                                'Risk from '
                                                                                'others\r\n'
                                                                                'Self-neglect\r\n'
                                                                                'Risk-taking or '
                                                                                'impulsive '
                                                                                'behaviour\r\n'
                                                                                'Risk related to '
                                                                                'dependants\r\n'
                                                                                'Safeguarding '
                                                                                'concerns\r\n'
                                                                                'Protective '
                                                                                'factors\r\n'
                                                                                'Reasons for '
                                                                                'living\r\n'
                                                                                'Support '
                                                                                'available\r\n'
                                                                                "Patient's stated "
                                                                                'ability to remain '
                                                                                'safe\r\n'
                                                                                'Any agreed safety '
                                                                                'plan\r\n'
                                                                                '\r\n'
                                                                                'Past psychiatric '
                                                                                'history:\r\n'
                                                                                'Previous mental '
                                                                                'health '
                                                                                'diagnoses\r\n'
                                                                                'Previous '
                                                                                'episodes\r\n'
                                                                                'Previous contact '
                                                                                'with mental '
                                                                                'health '
                                                                                'services\r\n'
                                                                                'Previous '
                                                                                'psychiatric '
                                                                                'admissions\r\n'
                                                                                'Previous '
                                                                                'psychological '
                                                                                'therapy\r\n'
                                                                                'Previous '
                                                                                'psychiatric '
                                                                                'medication and '
                                                                                'response\r\n'
                                                                                'Previous adverse '
                                                                                'effects from '
                                                                                'psychiatric '
                                                                                'medication\r\n'
                                                                                '\r\n'
                                                                                'Past medical '
                                                                                'history:\r\n'
                                                                                'List of pmh\r\n'
                                                                                '\r\n'
                                                                                'Medications:\r\n'
                                                                                'List of '
                                                                                'medications\r\n'
                                                                                'Include '
                                                                                'adherence, '
                                                                                'effectiveness and '
                                                                                'adverse effects '
                                                                                'if discussed\r\n'
                                                                                '\r\n'
                                                                                'Allergies:\r\n'
                                                                                'List of allergies '
                                                                                'and reactions if '
                                                                                'discussed\r\n'
                                                                                '\r\n'
                                                                                '\r\n'
                                                                                '\r\n'
                                                                                'Red Flags:\r\n'
                                                                                'Document the '
                                                                                'presence of the '
                                                                                'following;\r\n'
                                                                                'Feelings of '
                                                                                'hopelessness / '
                                                                                'guilt / better '
                                                                                'off not around\r\n'
                                                                                'Explicit suicidal '
                                                                                'ideation / '
                                                                                'history of the '
                                                                                'same\r\n'
                                                                                'Explicit self '
                                                                                'harm / history of '
                                                                                'the same\r\n'
                                                                                'Psychotic or '
                                                                                'manic features.',
                                                                 'section_order': 2},
                                                                {'section_key': 'family_history',
                                                                 'instruction': 'Family history of '
                                                                                'mental health '
                                                                                'problems',
                                                                 'section_order': 3},
                                                                {'section_key': 'social_history',
                                                                 'instruction': 'Details of '
                                                                                'their;\r\n'
                                                                                'Housing (where, '
                                                                                'what, with '
                                                                                'whom)\r\n'
                                                                                'Relationships '
                                                                                '(who, family '
                                                                                'friends)\r\n'
                                                                                '  - Postive '
                                                                                'relationships \r\n'
                                                                                '  - Negative '
                                                                                'relationships\r\n'
                                                                                'Presence of '
                                                                                'children / who '
                                                                                'has parental '
                                                                                'responsibilty\r\n'
                                                                                'Drug and alcohol '
                                                                                'use details.',
                                                                 'section_order': 4},
                                                                {'section_key': 'examination',
                                                                 'instruction': 'Document only '
                                                                                'examination '
                                                                                'findings '
                                                                                'explicitly stated '
                                                                                'in the transcript '
                                                                                'or dictated by '
                                                                                'the doctor.\r\n'
                                                                                'Do not infer '
                                                                                'examination '
                                                                                'findings.\r\n'
                                                                                'Each finding '
                                                                                'needs a new '
                                                                                'line.\r\n'
                                                                                'Include any '
                                                                                'observations that '
                                                                                'were measured '
                                                                                'during the '
                                                                                'consultation.\r\n'
                                                                                'Appearance and '
                                                                                'behaviour:\r\n'
                                                                                'Engagement and '
                                                                                'rapport:\r\n'
                                                                                'Eye contact:\r\n'
                                                                                'Psychomotor '
                                                                                'activity:\r\n'
                                                                                'Speech:\r\n'
                                                                                'Subjective '
                                                                                'mood:\r\n'
                                                                                'Objective '
                                                                                'mood:\r\n'
                                                                                'Affect:\r\n'
                                                                                'Thought form:\r\n'
                                                                                'Thought '
                                                                                'content:\r\n'
                                                                                'Perception:\r\n'
                                                                                'Cognition:\r\n'
                                                                                'Insight:\r\n'
                                                                                'Judgement:\r\n'
                                                                                'Capacity:',
                                                                 'section_order': 5},
                                                                {'section_key': 'comment',
                                                                 'instruction': 'The overall '
                                                                                'impression of the '
                                                                                'doctor, including '
                                                                                'any working '
                                                                                'diagnosis and '
                                                                                'differentials.\r\n'
                                                                                'Do not add a '
                                                                                'diagnosis or '
                                                                                'differential '
                                                                                'unless explicitly '
                                                                                'stated or clearly '
                                                                                'dictated by the '
                                                                                'doctor.\r\n'
                                                                                'Include the '
                                                                                "doctor's "
                                                                                'assessment of '
                                                                                'risk, using the '
                                                                                "doctor's own "
                                                                                'level of concern '
                                                                                'if stated.\r\n'
                                                                                'Include any '
                                                                                'assessment of '
                                                                                'capacity, '
                                                                                'safeguarding or '
                                                                                'need for urgent '
                                                                                'intervention if '
                                                                                'discussed.\r\n'
                                                                                'Include any '
                                                                                'explanations '
                                                                                'given to the '
                                                                                'patient.\r\n'
                                                                                'Then the plan '
                                                                                'that was '
                                                                                'discussed with '
                                                                                'the patient and '
                                                                                'things that the '
                                                                                'patient has '
                                                                                'agreed to do.\r\n'
                                                                                'Include '
                                                                                'medication '
                                                                                'started, stopped '
                                                                                'or changed, '
                                                                                'including dose '
                                                                                'and titration '
                                                                                'instructions.\r\n'
                                                                                'Include '
                                                                                'psychological '
                                                                                'therapy, social '
                                                                                'prescribing, '
                                                                                'lifestyle advice '
                                                                                'or self-help '
                                                                                'resources '
                                                                                'discussed.\r\n'
                                                                                'Include referrals '
                                                                                'made or '
                                                                                'considered, '
                                                                                'including NHS '
                                                                                'Talking '
                                                                                'Therapies, '
                                                                                'community mental '
                                                                                'health team, '
                                                                                'crisis team, '
                                                                                'psychiatry, '
                                                                                'safeguarding or '
                                                                                'emergency '
                                                                                'services.\r\n'
                                                                                'Include follow-up '
                                                                                'arrangements and '
                                                                                'timeframe.\r\n'
                                                                                'Then the safety '
                                                                                'netting that was '
                                                                                'provided.\r\n'
                                                                                'Document crisis '
                                                                                'advice exactly as '
                                                                                'discussed, '
                                                                                'including who the '
                                                                                'patient was '
                                                                                'advised to '
                                                                                'contact and under '
                                                                                'what '
                                                                                'circumstances.\r\n'
                                                                                'Do not state that '
                                                                                'crisis numbers or '
                                                                                'emergency advice '
                                                                                'were provided '
                                                                                'unless this '
                                                                                'occurred in the '
                                                                                'transcript.',
                                                                 'section_order': 6},
                                                                {'section_key': 'tasks',
                                                                 'instruction': 'Generate a list '
                                                                                'of tasks that the '
                                                                                'doctor will need '
                                                                                'to do based on '
                                                                                'the '
                                                                                'discussion.\r\n'
                                                                                'Each task needs a '
                                                                                'new line.\r\n'
                                                                                'Only generate '
                                                                                'tasks that arise '
                                                                                'explicitly from '
                                                                                'the '
                                                                                'consultation.\r\n'
                                                                                'Include '
                                                                                'prescriptions, '
                                                                                'medication '
                                                                                'changes, repeat '
                                                                                'tests, referrals, '
                                                                                'advice and '
                                                                                'guidance '
                                                                                'requests, '
                                                                                'letters, forms, '
                                                                                'result '
                                                                                'notifications, '
                                                                                'liaison with '
                                                                                'other services, '
                                                                                'record requests '
                                                                                'and planned '
                                                                                'follow-up '
                                                                                'actions.\r\n'
                                                                                'Include the '
                                                                                'intended '
                                                                                'timeframe where '
                                                                                'stated.\r\n'
                                                                                'Do not create '
                                                                                'tasks for actions '
                                                                                'that have already '
                                                                                'been completed '
                                                                                'unless further '
                                                                                'action is '
                                                                                'required.\r\n'
                                                                                'Do not create '
                                                                                'vague tasks such '
                                                                                'as "monitor" '
                                                                                'unless the method '
                                                                                'and timeframe '
                                                                                'were discussed.',
                                                                 'section_order': 7},
                                                                {'section_key': 'investigations',
                                                                 'instruction': 'Any blood tests '
                                                                                'that are planned, '
                                                                                'as comma '
                                                                                'separated list. '
                                                                                '(FBC, U&E, LFT '
                                                                                'etc)\r\n'
                                                                                'Include other '
                                                                                'planned '
                                                                                'investigations in '
                                                                                'the same comma '
                                                                                'separated list '
                                                                                'only if '
                                                                                'explicitly '
                                                                                'discussed.\r\n'
                                                                                'Only include '
                                                                                'future '
                                                                                'investigations '
                                                                                'that are planned '
                                                                                'or requested.\r\n'
                                                                                'Do not include '
                                                                                'investigations '
                                                                                'that have already '
                                                                                'been completed '
                                                                                'unless they are '
                                                                                'being '
                                                                                'repeated.\r\n'
                                                                                'Do not include '
                                                                                'result values, '
                                                                                'explanations, '
                                                                                'dates or '
                                                                                'management plans '
                                                                                'in this section.',
                                                                 'section_order': 8}]}}},
               {'name': 'Dictation cleaner',
                'description': 'Cleans up dictations',
                'latest_version': {'mode': 'freeform',
                                   'prompt_text': 'You are a medical scribe in the UK. Please '
                                                  'format the follow dictation, minimal changes to '
                                                  'wording and structure, only change those if '
                                                  'there is instruction. \r\n'
                                                  'Use lines breaks, punctuation as you see fit. '
                                                  'The idea is to make it polished and '
                                                  'professional and flow smoothly',
                                   'config_json': None}}]}

BUILTIN_QUICK_ACTION_BUNDLE = {'format': 'openscribe-quick-action-bundle',
 'format_version': 1,
 'quick_actions': [{'name': 'Physio Referral',
                    'description': 'A referral letter to physio therapy',
                    'latest_version': {'mode': 'freeform',
                                       'prompt_text': 'I am referring this {patient demographics} '
                                                      'with a {timeline} history of {symptoms}.\r\n'
                                                      'They are struggling with {functional '
                                                      'impact}.\r\n'
                                                      'They have tried {previous interventions} '
                                                      'with {outcome}.\r\n'
                                                      'On examination there is {signs and exam '
                                                      'findings}.\r\n'
                                                      'I have asked them to {proposed plan}.\r\n'
                                                      '{thank them for assessment}\r\n'
                                                      '\r\n'
                                                      'No niceties or intro, just the letter '
                                                      'content.'}},
                   {'name': 'Referral letter',
                    'description': 'Draft a referral letter from the consultation.',
                    'latest_version': {'mode': 'freeform',
                                       'prompt_text': 'Draft a referral letter using the '
                                                      'consultation context. Include reason for '
                                                      'referral, relevant history, examination, '
                                                      'investigations, current plan, and requested '
                                                      'action. Do not invent details. No '
                                                      'introductions or letter heading / sign '
                                                      'off. \r\n'
                                                      'The overall structure should be;\r\n'
                                                      'Hi can you send this to {speciality}\r\n'
                                                      '\r\n'
                                                      'I am referring this {age, sex} with '
                                                      'suspected {differential}\r\n'
                                                      'They have a {time} history of {signs and '
                                                      'symptoms}\r\n'
                                                      'On examination there is {examination '
                                                      'findings, targeted, relevant}\r\n'
                                                      'They have tried {x}\r\n'
                                                      'I have asked them to {plan}\r\n'
                                                      'Thank you for your specialist assessment '
                                                      'and management.'}},
                   {'name': 'Patient follow-up message',
                    'description': 'Draft a short patient-facing follow-up message.',
                    'latest_version': {'mode': 'freeform',
                                       'prompt_text': 'Draft a concise patient-facing follow-up '
                                                      'message from the consultation, this is for '
                                                      'SMS so needs to be very short. no '
                                                      'introductions or sign off, this is already '
                                                      'added by the user. Use clear language, at a '
                                                      'reading age of 10. Avoid adding information '
                                                      'not present in the transcript or note.\r\n'
                                                      '\r\n'
                                                      'Today we discussed {problem/symptoms}\r\n'
                                                      'I asked you to / We agreed that.. '
                                                      '{intervention}\r\n'
                                                      'Follow up will be.. {follow up plan}\r\n'
                                                      'Feel free to adjust the exact wording to '
                                                      'make it seem more natural'}}]}
